### PR TITLE
Moved getMessageDetails to onSuccessDefault handler

### LINKED ISSUE #66: Task Return Result Content
I updated one of my application from `0.0.10` to `0.0.14` and now running into issue where my custom `onSuccess` function is not able to access the `result` content. Here is a snapshot of it:
``` js
function processSuccess(progressBarElement, progressBarMessageElement, result) {
		console.log('SUCCESS: ' + result)
		var search_id = result[0]
		var datasheet = result[1]
		var payload = {
			"search_id" : search_id,
			"datasheet" : datasheet,
		}
		console.log(payload)

                ....
}
```
(`result` is now empty).

And here is the task:
``` python
@shared_task(bind=True)
def ProcessDownload(self, manufacturer, part_number, search_id):
	progress_recorder = ProgressRecorder(self)
	progress_recorder.set_progress(0, 10, description='Initializing Request')
	time.sleep(1)

	spec = Specifications(task=self)
	spec.DownloadPDF(manufacturer, part_number)

	if not spec.datasheet:
		return [search_id, '']
	
	return [search_id, capspec.datasheet]
```

This code used to work and the `processSuccess` would capture the content of `result` but no anymore... I've added those debug prints to make sure the `processSuccess` method is called (which is the case).
I've also changed the task return value to a simple string for testing purpose and still nothing.

Any idea what am I missing? Was this setup wrong in the first place?
How should one efficiently implement the "communication" between the task return values and the `result` input of the `onSuccess` method?

### PR DESCRIPTION
**Pull request by eeintech**
If approved, fixes #66

### CODE REVIEW

**Review by czue — APPROVED** [review]

**Comment by eeintech** [comment]
What's missing for this PR to be merged?

**Comment by OmarWKH** [comment]
This PR along with #69 look good enough to fix the issue. I don't know if @EJH2 has further thoughts.

**Comment by czue** [comment]
sorry, no reason, was just giving time for others to review

**Comment by eeintech** [comment]
No problem, thanks for merging!

**Pull request merged**
